#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in8,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightDriveEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           leftRoller,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftDriveCenter, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftDriveFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightDriveCenter, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightRoller,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "MickDriverControl.h"
#include "MickAutonControl.h"
//#include "UART.h"



void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

  liftPotentiometer.minValue = 245;
  liftPotentiometer.maxValue = 270;

  clawPotentiometer.minValue = 28;
  clawPotentiometer.maxValue = 8;
}


task autonomous()
{
	SetDrive(127);
	wait1Msec(500);
	startTask(StarLift);
	SetDrive(-127);
	wait1Msec(250);
	SetDrive(0);
	startTask(UpdateSensors);

	startTask(OpenClaw);
	MoveForward(440);
	stopTask(OpenClaw);
	MoveBackward(-500);
	TurnLeft(110);
	startTask(LowLift);
	MoveForward(150);
	CloseClaw();

	wait1Msec(10000);
}


task usercontrol()
{

  while (true)
  {
  	Drive();
  	Lift();
  	Roller();
  }
}
