#pragma config(Motor,  port2,           leftDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftDriveCenter, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftDriveFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightDriveCenter, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "MickDriverControl.h"

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

}


task autonomous()
{

}


task usercontrol()
{

  while (true)
  {
  	Drive();
  }
}
