#pragma config(Sensor, in8,    gyro,           sensorAnalog)
#pragma config(Sensor, dgtl1,  Claw1,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  Claw2,          sensorDigitalOut)
#pragma config(Motor,  port2,           driveLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftLeftTop,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftLeftCenter, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeftBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRightTop,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftRightCenter, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftRightBottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRight,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define DEADZONE 25

void Drive();
void Lift();
void Pincer();


int globalMoveTime;
int globalMoveLeftPower;
int globalMoveRightPower;
int globalLiftPower;
int globalLiftTime;

task LiftTask();
task MoveTask();
void Move(int leftPower, int rightPower, int time);
void ActuateClaw(int state);
void Elevate(int power, int time);
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                          */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	ActuateClaw(1);

	globalLiftPower = 127;
	globalLiftTime = 1001;
	startTask(LiftTask);

	Move(127, 127, 1751);

	Move(-127, -127, 500);

	Move(-127, -127, 250);

	//90 degree turn left
	Move(-127, 127, 537);

	Elevate(-127, 750);

	//drive forward to pick up cube
	Move(127, 127, 1337);
	ActuateClaw(0);

	Elevate(127, 1001);

	Move(70, -70, 1001);

	Move(127, 127, 750);
	wait1Msec(1500);
	ActuateClaw(1);

	Move(-127, -127, 1000);
	Move(-127, 127, 1000);

	Elevate(-50, 1000);
	Elevate(50, 1000);


	/*
	ActuateClaw(1);
	Elevate(127, 277);
	//90 degree turn right
	Move(127, -127, 787);


	globalLiftPower = 127;
	globalLiftTime = 1327 - 277;
	startTask(LiftTask);
	Move(127, 127, 1117);

	ActuateClaw(0);
	/*
	//90 degrees turn left
	globalMoveLeftPower = -127;
	globalMoveRightPower = -127;
	globalMoveTime = 1117;
	startTask(MoveTask);
	Elevate(-127, (1327 - 997);

	Move(-127, 127, 787);
	Move(127, 127, 1117);
	Move(127, -127, 787);
	globalMoveLeftPower = 127;
	globalMoveRightPower = 127;
	globalMoveTime = 1117;
	startTask(MoveTask);
	Elevate(127, (1327 - 997));

*/
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		Drive();
		Lift();
		Pincer();
	}
}



void Drive()
{
	int rightPower = vexRT[Ch2];
	int leftPower = vexRT[Ch3];

	//rightPower = abs(rightPower) < DEADZONE ? 0 : rightPower;
	//leftPower = abs(leftPower) < DEADZONE ? 0 : leftPower;

	motor[port9] = rightPower;
	motor[driveLeft] = leftPower;

}

void Lift()
{
	if(vexRT[Btn6U])
	{
		//up
		motor[liftRightBottom] = 127;
		motor[liftRightCenter] = 127;
		motor[liftRightTop] = 127;

		motor[liftLeftBottom] = 127;
		motor[liftLeftCenter] = 127;
		motor[liftLeftTop] = 127;
	}
	else if(vexRT[Btn6D])
	{
		//down
		motor[liftRightBottom] = -127;
		motor[liftRightCenter] = -127;
		motor[liftRightTop] = -127;

		motor[liftLeftBottom] = -127;
		motor[liftLeftCenter] = -127;
		motor[liftLeftTop] = -127;
	}
	else
	{
		//stop
		motor[liftRightBottom] = 0;
		motor[liftRightCenter] = 0;
		motor[liftRightTop] = 0;

		motor[liftLeftBottom] = 0;
		motor[liftLeftCenter] = 0;
		motor[liftLeftTop] = 0;
	}
}

void Pincer()
{
	if(vexRT[Btn5U])
	{
		//close
		SensorValue[Claw1] = 0;
		SensorValue[Claw2] = 0;
	}
	else if(vexRT[Btn5D])
	{
		//open
		SensorValue[Claw1] = 1;
		SensorValue[Claw2] = 1;
	}
}

void Move(int leftPower, int rightPower, int time)
{
	motor[driveLeft] = leftPower;
	motor[port9] = rightPower;
	wait1Msec(time);
	motor[driveLeft] = 0;
	motor[port9] = 0;
}

task MoveTask()
{
	Move( globalMoveLeftPower, globalMoveRightPower, globalMoveTime);
}

task LiftTask()
{
	Elevate(globalLiftPower, globalLiftTime);
}

void ActuateClaw(int state)
{
	SensorValue[Claw1] = state;
	SensorValue[Claw2] = state;
	wait1Msec(499);
}

void Elevate(int power, int time)
{
	motor[liftRightBottom] = power;
	motor[liftRightCenter] = power;
	motor[liftRightTop] = power;

	motor[liftLeftBottom] = power;
	motor[liftLeftCenter] = power;
	motor[liftLeftTop] = power;

	wait1Msec(time);
	power = 0;
	motor[liftRightBottom] = power;
	motor[liftRightCenter] = power;
	motor[liftRightTop] = power;

	motor[liftLeftBottom] = power;
	motor[liftLeftCenter] = power;
	motor[liftLeftTop] = power;



	}
