#pragma config(Sensor, dgtl1,  leftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightDrive,     sensorQuadEncoder)
#pragma config(Motor,  port1,           leftClaw,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           left3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           right3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightClaw,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "driverControl.h"
#include "autonControl.h"
#include "UART.h"

void pre_auton()
{
	bStopTasksBetweenModes = false;

}

task autonomous()
{
		// Setup the UART ports
  	configureSerial();

  	while(true){
		motor[port1] = motorPowers[0];
		motor[port2] = motorPowers[1];
		motor[port3] = motorPowers[2];
		motor[port4] = motorPowers[3];
		motor[port5] = motorPowers[4];
		motor[port6] = motorPowers[5];
		motor[port7] = motorPowers[6];
		motor[port8] = motorPowers[7];
		motor[port9] = motorPowers[8];
		motor[port10] = motorPowers[9];
		}

}

task usercontrol()
{
  // User control code here, inside the loop
  while (true)
  {
    drive();
    lift();
    claw();
  }
}
