#pragma config(Sensor, in2,    LED,            sensorVexIQ_LED)
#pragma config(Sensor, in7,    gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  port3,           leftDrive1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightDrive1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftDrive2,    tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port6,           rightDrive2,   tmotorVex393_HBridge, openLoop, driveRight, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Robot.h"
#include "AutonFunctions.h"
#include "Enums.h"
#include "EnumsFunctions.h"
//#include "Vector2.h"
//moves robot to random coordinates
task main()
{
	Initialize(Bot,leftDriveEnc, rightDriveEnc);
	startTask(UpdatePosition);

	//test movement with random points
	/*while(true)
	{
	Move(rand() % 50 + 20, rand() % 50 + 20);
	Stop();
	Move(0, 0);
	Stop();
	}*/

	//FSM
	States state = Start;
	while(true)
	{
		switch(state)
		{
		case Start:
			state = IdleRobot;
			break;

		case IdleRobot:
			IdleRobotState(&state);
			break;

		case FindObj:
			FindObjState(&state);
			break;

		case GoToObj:
			GoToObjState(&state);
			break;

		case GrabObj:
			GrabObjState(&state);
			break;

		case UpdateMap:
			UpdateMapState(&state);
			break;

		case GoToFence:
			GoToFenceState(&state);
			break;
		case Score:
			ScoreState(&state);
			break;

		}
	}
}
