#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in8,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightDriveEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           leftRoller,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftDriveCenter, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftDriveFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightDriveCenter, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightRoller,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//leftDrive1,leftDrive2,
//Gyro
#include "Robot.h"
#include "AutonFunctions.h"
#include "Enums.h"
#include "EnumsFunctions.h"
//#include "Vector2.h"
//moves robot to random coordinates
task main()
{
	Initialize(Bot,leftDriveEnc, rightDriveEnc);
	startTask(UpdatePosition);

	//test movement with random points
	/*while(true)
	{
	Move(rand() % 50 + 20, rand() % 50 + 20);
	Stop();
	Move(0, 0);
	Stop();
	}*/

	//FSM
	States state = Start;
	while(true)
	{
		switch(state)
		{
		case Start:
			state = IdleRobot;
			break;

		case IdleRobot:
			state = IdleRobotState(state);
			break;

		case FindObj:
			state = FindObjState(state);
			break;

		case GoToObj:
		state =	GoToObjState(state);
			break;

		case GrabObj:
			state =GrabObjState(state);
			break;

		case UpdateMap:
			state =UpdateMapState(state);
			break;

		case GoToFence:
			state =GoToFenceState(state);
			break;

		case Score:
			state =ScoreState(state);
			break;

		}
	}
}
