#pragma config(UART_Usage, UART2, uartUserControl, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <UART.h>

int currentAngle;


task angleReading(){
	while(true){
		currentAngle = jetsonSensors.yaw;
  }
}

task main()
{
	startTask(angleReading);
	while(true){
		//
  }

}
