#pragma config(UART_Usage, UART2, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, in1,    C_POT,          sensorPotentiometer)
#pragma config(Sensor, in2,    L_POT,          sensorPotentiometer)
#pragma config(Sensor, dgtl5,  R_ENC,          sensorQuadEncoder)
#pragma config(Sensor, dgtl11, L_ENC,          sensorQuadEncoder)
#pragma config(Motor,  port1,           claw1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           ld1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ld2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ld3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rd1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rd2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rd3,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <UART.h>
#include <AutonFunctions.h>
#include <sensorFunctions.h>
#include <autoRoutines.h>
#include <worldsBotManual.h>

int angle = 0;
void gyroTest(){

	//	rotateToAngle(UTurn);
	wait10Msec(100);

	Turn(angle);
	angle += 90;
	wait10Msec(100);

	//rotateToAngle(turnRight);
}

void moveTest()
{
	Move(10, -10);
}

task main()
{

	configureSerial();
	startTask(UpdatePosition);
	Initialize(Bot, leftDriveEnc, rightDriveEnc);
	while(true){
		if(vexRT[Btn7U] == 1){
			wait10Msec(50);
			gyroTest();
		}
		if(vexRT[Btn7D] == 1){
			wait10Msec(50);
			moveTest();
		}
	}

}
