#pragma config(Sensor, in1,    C_POT,          sensorPotentiometer)
#pragma config(Sensor, in7,    L_POT,          sensorPotentiometer)
#pragma config(Sensor, dgtl11, L_ENC,          sensorQuadEncoder)
#pragma config(Motor,  port1,           claw1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           ld1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ld2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ld3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rd1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rd2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rd3,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <worldsBotManual.h>
#include <sensorFunctions.h>
#include <autoRoutines.h>
#include <UART.h>

void Open_Close_Claw(int power,int wide){

	//Close Claw
	while (SensorValue[C_POT] > wide && SensorValue[C_POT] < OPEN_CLAW_LIMIT){

		motor[claw1] = -power;
		motor[claw2] = -power;

	}

	motor[claw1] = 0;
	motor[claw2] = 0;
	wait10Msec(50);


	//Open Claw
	while(SensorValue[C_POT] < wide && SensorValue[C_POT] < OPEN_CLAW_LIMIT){

		motor[claw1] = power;
		motor[claw2] = power;

	}

	motor[claw1] = 0;
	motor[claw2] = 0;
	wait10Msec(50);


}

void ClawTest(){

	Open_Close_Claw(50,MID_OPEN_CLAW);

	wait10Msec(50);

	Open_Close_Claw(50,WIDE_CLAW_OPEN);

	wait10Msec(50);

	Open_Close_Claw(50,CLOSE_CLAW);
}

void LiftTest(){
	motor[lift1] = -maxpower;
	motor[lift2] = -maxpower;
	while(SensorValue[L_POT] < HIGHLIFTLIMIT){

	}

	motor[lift1] = 0;
	motor[lift2] = 0;

	wait1Msec(1000);

	stopTask(claw);
	ClawTest();
	startTask(claw);

	motor[lift1] = maxpower;
	motor[lift2] = maxpower;
	while(SensorValue[L_POT] > LOWLIFTLIMIT){

	}

	motor[lift1] = 0;
	motor[lift2] = 0;
}


task main()
{
	startTask(drive);
	startTask(lift);
	startTask(claw);
	startTask(SensorReader);

	wait10Msec(50);


	while(true){
		if(vexRT[Btn7U] == 1){
			stopTask(drive);
			stopTask(lift);
			stopTask(claw);
			wait10Msec(40);
			RightSquareAuton2();
			//LiftTest();
			startTask(lift);
			startTask(drive);
			startTask(claw);
		}
	}


}
