//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Robot.h"
#include "AutonFunctions.h"
//moves robot to random coordinates
task main()
{
	Initialize(Bot,leftDriveEnc, rightDriveEnc);
	startTask(UpdatePosition);

	while(true)
	{
		Move(rand() % 50 + 20, rand() % 50 + 20);
		Stop();
		Move(0, 0);
		Stop();
	}
}
