#pragma config(Motor,  port1,           claw1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           ld1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ld2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ld3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rd1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rd2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rd3,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define deadzone 30
#define maxpower 127

task drive(){
	while(true){

		int leftStick = vexRT[Ch3];
		int rightStick = vexRT[Ch2];

		if(abs(leftStick) <= deadzone)
			leftStick = 0;

		if(abs(rightStick) <= deadzone)
			rightStick = 0;

		motor[ld1] = leftStick;
		motor[ld2] = leftStick;
		motor[ld3] = leftStick;

		motor[rd1] = rightStick;
		motor[rd2] = rightStick;
		motor[rd3] = rightStick;

	}
}

task lift(){
	while(true){

		if(vexRT[Btn6D] == 1){
			motor[lift1] = maxpower;
			motor[lift2] = maxpower;
		}
		else if(vexRT[Btn6U] == 1){
			motor[lift1] = -maxpower;
			motor[lift2] = -maxpower;
		}
		else {
			motor[lift1] = 0;
			motor[lift2] = 0;
		}
	}

}

task claw(){
	while(true){

		if(vexRT[Btn5U] == 1){
			motor[claw1] = maxpower;
			motor[claw2] = maxpower;
		}
		else if(vexRT[Btn5D] == 1){
			motor[claw1] = -maxpower;
			motor[claw2] = -maxpower;
		}
		else{
			motor[claw1] = 0;
			motor[claw2] = 0;
		}
	}
}
task main()
{

	startTask(drive);
	startTask(lift);
  startTask(claw);

	while(true);
}
